### ISSUE TITLE
rev_A (from No-Face)

### ISSUE THREAD

**Issue by stefantan18** [jwongUlti25/WHAMo#3]
It is clear how a user would interact with the data. However, it is slightly unclear what the functions are of each widget. Other than that, the interactions are very compelling and would lead to users to continue exploring the data.

**Comment by johnnywong30** [comment]
A widget such as the radio button would be used to zoom in on the map of NYC to get a better view of the map. It would also help distinguish the points and show the distances from each accident on the map.
